"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = '▶▶ '

format = """
$shell\
($username)\
$directory\
($git_branch$git_status[\ue0b0](fg:#55d2fa))\
$cmd_duration\
$line_break\
$character\
"""

[shell]
format = """
[\u256d\u2500](fg:#e0f8ff)\
[\ue0b6](fg:#fa55e7)\
[ $indicator ](fg:#ffffff bg:#fa55e7)\
[\ue0b0](fg:#fa55e7 bg:#555555)\
"""
disabled = false

[username]
format = """
\b\
[\ue0b0](fg:#fa55e7 bg:#ef5350)\
[ \uf0e7 $user ](fg:#fffb38 bg:#ef5350)\
[\ue0b0](fg:#ef5350 bg:#555555)\
"""
disabled = false
show_always = false

[directory]
format = "[ $path ](fg:#e4e4e4 bg:#555555)[\ue0b0](fg:#555555)"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…/"
home_symbol = "~"
use_os_path_sep = false

[git_branch]
format = """
\b\
[\ue0b0](fg:#555555 bg:#55d2fa)\
[ $symbol$branch(:$remote_branch) ](bg:#55d2fa fg:#353535)\
"""
symbol = "\ue0a0 "

[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""
untracked = "?$count"
stashed = "$"
modified = "!$count"
staged = "+$count"
renamed = "»"
deleted = "✘"
ignore_submodules = false
format = "([$all_status$ahead_behind$count ](bg:#55d2fa fg:#353535))"

[fill]
symbol = " "

[time]
disabled = false
format = "[\ue0b6[ \uf64f $time ](fg:#ffffff bg:#40c4ff)\ue0b4](fg:#40c4ff)"

[cmd_duration]
format = "[\ue0b6](fg:#303030)[ \uf252 $duration ](fg:#888860 bg:#303030)[\ue0b0](fg:#303030)"

[character]
format = """
[\u2570\u2500](fg:#e0f8ff)\
$symbol \
"""
success_symbol = "[\u276f](#0099fe)"
error_symbol = "[\u276f](#ff0000)"
